Project/Project/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;


namespace Project.Controllers
{
    public class PatientController : Controller
    {
        [HttpGet]
        public ActionResult AddorEdit(int id=0)
        {
            patient_Register patient_Register = new patient_Register();
            return View(patient_Register);
        }

        [HttpPost]
        public ActionResult AddorEdit(patient_Register patient_Register)
        {
            using(DbModel dbModel = new DbModel())
            {
                if(dbModel.patient_Register.Any(x => x.mob_Number == patient_Register.mob_Number))
                {
                    ViewBag.DuplicateMessage = "mobile number already exits";
                    return View("AddorEdit", patient_Register);
                }
                
                dbModel.patient_Register.Add(patient_Register);
                dbModel.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registration SuccessFull";
            return View("AddorEdit", new patient_Register());
        }

    }
}

Project/Project/Controllers/doctorregisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Project.Models;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class doctorregisterController : Controller
    {
        [HttpGet]
        public ActionResult DoctorRegister(int id = 0)
        {
            doctor_Register dreg = new doctor_Register();
            return View(dreg);
        }


        [HttpPost]

        public ActionResult DoctorRegister(doctor_Register doctor_Register)
        {
            using (mydbEntities mydbEntities=new mydbEntities())
            {
                if(mydbEntities.doctor_Register.Any(x => x.mob_Number == doctor_Register.mob_Number))
                {
                    ViewBag.DuplicateMessage = "mobile number already exits";
                    return View("DoctorRegister", new doctor_Register());
                }
                mydbEntities.doctor_Register.Add(doctor_Register);
                mydbEntities.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registration SuccessFull";
            return View("DoctorRegister", new doctor_Register());
            
        }

    }
        
  
}

Project/Project/Views/Patient/AddorEdit.cshtml
@model Project.Models.patient_Register

@{
    ViewBag.Title = "Patient Registration";
}

<h2>Patient Regestration</h2>


@using (Html.BeginForm("AddorEdit","Patient",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.first_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.first_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.first_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.last_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.last_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.last_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.mob_Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mob_Number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mob_Number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.email_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email_Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dob, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dob, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.sex, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sex, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sex, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-primary" />
           <p>Are You Doctor</p> @Html.ActionLink("Click Here","DoctorRegister","doctorregister")
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class="label-success">@ViewBag.SuccessMessage</label>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class="label-danger">@ViewBag.DuplicateMessage</label>
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
}