Project/Project/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;
namespace Project.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
       

        public ActionResult Details(int Id)
        {
            doctor_Register frnds = new doctor_Register();
             mydbEntities db = new mydbEntities();
            frnds = db.doctor_Register.Find(Id);
            return PartialView("_Details", frnds);
        }

        public ActionResult Index(string searching)
        {
            mydbEntities db = new mydbEntities();
            return View(db.doctor_Register.Where(x => x.city.Contains(searching) || searching == null).ToList());

        }
    }
}

Project/Project/Views/Demo/Details.cshtml
@model IEnumerable<Project.Models.doctor_Register>

<div>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">FriendsInfo</h4>
    </div>


    @foreach (var item in Model)
    {
        <p><label>Name: </label>@item.first_Name</p>
        <p><label>Last: </label>@item.last_Name</p>
        <p><label>city: </label>@item.city</p>
        <p><label>cost: </label>@item.cost</p>
        <p><label>specilization: </label>@item.specilization</p>

    }
</div>  

Project/Project/Views/Demo/Index.cshtml
@model IEnumerable<Project.Models.doctor_Register>
@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("View All", "Index")

@using (Html.BeginForm("Index", "Demo", FormMethod.Get))
{
    @Html.TextBox("searching")
    <input type="submit" value="search" />

}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.first_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.mob_Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.city)
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
    foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.first_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mob_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.city)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })*@

                <a href="#" class="anchorDetail" id="@item.mob_Number">Details</a>

            </td>
        </tr>
       }
    }

</table>


@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script>

        var TeamDetailPostBackURL = '/Demo/Details';
        $(function () {
            $(".anchorDetail").click(function () {
                debugger;
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('id');
                var options = { "backdrop": "static", keyboard: true };
                $.ajax({
                    type: "GET",
                    url: TeamDetailPostBackURL,
                    contentType: "application/json; charset=utf-8",
                    data: { "id": id },
                    datatype: "json",
                    success: function (data) {
                        debugger;
                        $('#myModalContent').html(data);
                        $('#myModal').modal(options);
                        $('#myModal').modal('show');

                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });


            $("#closbtn").click(function () {
                $('#myModal').modal('hide');
            });
        });

    </script>

}